# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       libtirpc

# >> macros
# << macros

Summary:    Transport Independent RPC library (SunRPC replacement)
Version:    1.3.3
Release:    0
Group:      Development/Libraries
License:    GPLv2
URL:        https://sourceforge.net/projects/libtirpc/
Source0:    %{name}-%{version}.tar.bz2
Source100:  libtirpc.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  autoconf
BuildRequires:  automake

%description
Libtirpc is a port of Suns Transport-Independent RPC library to Linux.
It's being developed by the Bull GNU/Linux NFSv4 project.

%if "%{?vendor}" == "chum"
Categories:
  - System
  - Library
Custom:
  PackageRepo: https://github.com/sailfishos-chum/libtirpc
%endif


%package doc
Summary:    Documentation files for %{name}
Group:      Documentation
Requires:   %{name} = %{version}-%{release}

%description doc
%{summary}.

%package devel
Summary:    Developmemt files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
%{summary}.

%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
./bootstrap
# << build pre

%configure --disable-static \
    --with-gnu-ld \
    --disable-gssapi

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%{_libdir}/*.so.*
%config %{_sysconfdir}/*
# >> files
# << files

%files doc
%defattr(-,root,root,-)
%{_mandir}/*/*
# >> files doc
# << files doc

%files devel
%defattr(-,root,root,-)
%{_includedir}/tirpc/*
%{_libdir}/*.so
%{_libdir}/pkgconfig/*
# >> files devel
# << files devel
